<?php
	require_once('../../miniframework/App/Utils.php');
	Utils::verificarLogado();
?>
<nav class="">
	<div class="d-flex justify-content-start" style="padding: 5px;">
		<i class="fas fa-home fa-2x" style="cursor: pointer;color: #1da1f2;"></i>
	</div>
</nav>



<div class="container mt-5">
	<div class="row">

		<!-- topo imagem,seguidores,postagens ,seguindo -->
		<div class="col-md-12">
			<div id="wallpaper">
				<div id="profile">
					<div class="perfilTopo">
						<form method="post" enctype="multipart/form-data" id="uploadPic">
							<input type="file" name="imgInp" accept="image/x-png,image/jpge,image/jpg" id="imgInp" hidden>
							<div class="pictureContainer">
								<img id="userImg" src="../public/img/user/<?php echo $this->view->user_picture ?>" />
								<label for="imgInp"></label>
							</div>
						</form>
					</div>


				</div>
			</div>
		</div>


		<div class="col-md-12">
			<div class="d-flex align-sitems-center justify-content-end">


				<i style="cursor: pointer;" class="fas fa-image fa-2x" onclick='$("#containerEscolhaImagem").show();'></i>

			</div>
		</div>



		<div class="col-md-12">
			<div class="perfilPainel">

				<div class="row mt-2 mb-2">
					<div class="col mb-2">
						<span class="perfilPainelNome"><?= $this->view->info_usuario['nome'] ?></span>
					</div>
				</div>

				<div class="row mb-2">

					<div class="col">
						<span class="perfilPainelItem">Postagens</span><br />
						<span class="perfilPainelItemValor">10</span>
					</div>

					<div class="col">
						<span class="perfilPainelItem">Seguindo</span><br />
						<span class="perfilPainelItemValor">18</span>
					</div>

					<div class="col">
						<span class="perfilPainelItem">Seguidores</span><br />
						<span class="perfilPainelItemValor">2</span>
					</div>

				</div>

			</div>
		</div>

		<div id="bordaPerfil">

		</div>



		<div class="col-md-12">
			<div id="galeria">
				<!-- Grid row -->
				<div class="row">

					<!-- Grid column -->
					<div class="col-md-12 d-flex justify-content-center mb-5">

						<button type="button" class="btn btn-outline-black waves-effect filter" data-rel="all">All</button>
						<button type="button" class="btn btn-outline-black waves-effect filter" data-rel="1">Mountains</button>
						<button type="button" class="btn btn-outline-black waves-effect filter" data-rel="2">Sea</button>

					</div>
					<!-- Grid column -->

				</div>
				<!-- Grid row -->

				<!-- Grid row -->
				<div class="gallery" id="gallery">

					<!-- Grid column -->

					<div class="mb-3 pics animation all 2">
						<img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(73).jpg" alt="Card image cap">
					</div>
					<!-- Grid column -->

					<!-- Grid column -->
					<div class="mb-3 pics animation all 1">
						<img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Vertical/mountain1.jpg" alt="Card image cap">
					</div>
					<!-- Grid column -->

					<!-- Grid column -->
					<div class="mb-3 pics animation all 1">
						<img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Vertical/mountain2.jpg" alt="Card image cap">
					</div>
					<!-- Grid column -->

					<!-- Grid column -->
					<div class="mb-3 pics animation all 2">
						<img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(35).jpg" alt="Card image cap">
					</div>
					<!-- Grid column -->

					<!-- Grid column -->
					<div class="mb-3 pics animation all 2">
						<img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(18).jpg" alt="Card image cap">
					</div>
					<!-- Grid column -->

					<!-- Grid column -->
					<div class="mb-3 pics animation all 1">
						<img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Vertical/mountain3.jpg" alt="Card image cap">
					</div>
					<!-- Grid column -->

				</div>
				<!-- Grid row -->

			</div>




		</div>

	</div>
</div>



<div id="containerEscolhaImagem" style="clear:both">
	<div class="row"> 
		<figure  class="col-4">
			<div style="position:relative">
				<div class="divSelecionada"></div>
				<img class="img-fluid" alt="picture" src="../public/img/wallpapers/wallpaperPadrao/1.png" >
			</div>
		</figure>
	 
		<figure  class="col-4">
			<div style="position:relative">
				<div class="divSelecionada"></div>
				<img class="img-fluid" alt="picture" src="../public/img/wallpapers/wallpaperPadrao/2.png"/>
			</div>
		</figure>
	 
		<figure class="col-4">
			<div style="position:relative">
				<div class="divSelecionada"></div>
				<img class="img-fluid" alt="picture" src="../public/img/wallpapers/wallpaperPadrao/3.png"  />
			</div>
		</figure>
	</div>

	<div class="row">

		<figure class="col-4">
			<div style="position:relative">
				<div class="divSelecionada"></div>
				<img class="img-fluid" alt="picture" src="../public/img/wallpapers/wallpaperPadrao/4.png"  />
			</div>
		</figure>

		<figure class="col-4">
			<div style="position:relative">
				<div class="divSelecionada"></div>
				<img class="img-fluid" alt="picture" src="../public/img/wallpapers/wallpaperPadrao/5.png"  />
			</div>
		</figure>

		<figure class="col-4">
			<div style="position:relative">
				<div class="divSelecionada"></div>
				<img class="img-fluid" alt="picture" src="../public/img/wallpapers/wallpaperPadrao/6.png" />
			</div>
		</figure>

	</div>

	<div class="col-md-12 mt-4" style="clear:both">
		<div id="containerUploadWallpaper" class="">
			
			<form class="align-items-end mb-auto mt-0 d-flex justify-content-end" method="post" enctype="multipart/form-data" id="formularioUploadWallpaper">
 
			   <p  style="position:absolute;left:3px;cursor:pointer;" id="adicionarSelecionada"  >Adicionar Selecionada</p>
			 
			   <input type="file" name="uploadWallpaper" accept="image/*" id="uploadWallpaper" hidden />
			   
			   <label id="boxEscolherImagem" for="uploadWallpaper" class="d-flex align-items-center">

					<span class="">Upload do fundo </span>

					<i class="fas fa-image fa-2x"></i>
				</label>
			</form>
		</div>
	</div>
</div>



<div id="visualizarImagem" onclick="fecharPreviewImagem()">
	<div class="d-flex justify-content-end">
		<i onclick="fecharPreviewImagem()" style="margin:5px;cursor:pointer" class="fas fa-times fa-3x"></i>
	</div>

	<div id="wallpaperUploadPreview" class="d-flex align-items-center justify-content-center">
		<img id="imgWallpaperPreview" alt="picture" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(118).jpg" class="img-fluid" />
	</div>
</div>