<?php
use MF\Controller\Action;
use MF\Model\Container;

$usuarioCurtiu=$_SESSION['id'];
$curtida=Container::getModel('curtida');
date_default_timezone_set('America/Sao_Paulo');
$comentarios=Container::getModel('comentario');
$comentariosDosComentarios=Container::getModel('ComentarComentarios');

 ?>

<div class="postagemContainer" class="row postagem">
    <div class="col">

        <img style="cursor:pointer" onclick="location.href='/miniframework/public/perfil?idUsuario=<?= $postagem['usuarioId']?>'" class="imgPostagem" src="../public/img/user/<?= $postagem['picture'] ?>">

        <p   style="display:inline" class="nomeUsuarioPostagem"><strong onclick="location.href='/miniframework/public/perfil?idUsuario=<?=$postagem['usuarioId']?>'" style="cursor:pointer"><?= $postagem['name'] ?></strong><small> <span class="text text-muted">- <?= $postagem['data'] ?></span></small></p>
        <?php if($this->view->user_id == $postagem['usuarioId']){ ?>
            <span onclick="excluirPost(<?=$postagem['postagemId']?>)" style="position:absolute;right:0px; cursor:pointer"><i class="fas fa-trash"></i></span>
        <?php }?>

        <div  style="display: inline; margin:0px 5px">
            <span onclick="location.href='/miniframework/public/denunciarpostagem?idPostagem=<?=$postagem['postagemId']?>'" style="cursor:pointer" class="denunciarPostagem"><i class="far fa-flag"></i></span>
            <p style="color:#7E7786; font-size: 12px; display:inline;opacity:0">denunciar postagem</p>
        </div>

        <p style="margin-top:14px"><?= $postagem['textoPostagem']?></p>

        
        <!-- //Postagens VIdeo/Foto -->
        <div class="containerVideoEImagem" style="position:relative">


            <?php if ($postagem['arquivo'] != ''  &&  strpos($postagem['arquivo'], '.mp4') != 0) {  ?>


                <video id="video<?php echo str_replace('.mp4', '', $postagem['arquivo']) ?>" class="img-fluid">
                    <source src="../public/img/uploads/postagens/<?= $postagem['arquivo'] ?>" type="video/mp4">
                </video>


                <i id="buttonVideoPlay<?= str_replace('.mp4', '', $postagem['arquivo']) ?>" onclick="videoplay('video<?php echo str_replace('.mp4', '', $postagem['arquivo']) ?>','buttonVideoPlay<?= str_replace('.mp4', '', $postagem['arquivo']) ?>')" class="fas fa-play fa-2x buttonVideoPlay"></i>
                <i id="buttonVideoRestart<?php echo str_replace('.mp4', '', $postagem['arquivo']) ?>" onclick="restart('video<?php echo str_replace('.mp4', '', $postagem['arquivo']) ?>')" class="fas fa-undo-alt fa-lg buttonVideoRestart"></i>
                <i id="buttonVideoVolume<?php echo str_replace('.mp4', '', $postagem['arquivo']) ?>" onclick="volume('video<?php echo str_replace('.mp4', '', $postagem['arquivo']) ?>','buttonVideoVolume<?php echo str_replace('.mp4', '', $postagem['arquivo']) ?>')" class="fas fa-volume-up fa-lg buttonVideoVolume"></i>





            <?php } else { ?>
                <?php if ($postagem['arquivo'] != '') { ?>
                    <img src="../public/img/uploads/postagens/<?= $postagem['arquivo'] ?>" style="margin:0px auto" class="img-fluid d-flex justify-content-center">
                <?php } ?>
            <?php } ?>

        </div>

        <br />

        <!-- <form class="formRemoverPostagem">
                <div class="col d-flex justify-content-end">
                    <a href="/remover?id_remover=<?= $postagem['id'] ?>" class="btn btn-danger"><small>Remover</small></a>
                </div>
            </form> -->

        <!-- //comentarios likes e compartilhar -->
        <div class="row">
            <div class="col">
                <div id="postagemOutros">

                    <div style="position: relative;">
                        <span onclick="curtir('curtirPost<?php echo $postagem['postagemId'] ?>','<?= $postagem['postagemId'] ?>','<?= $usuarioCurtiu ?>')">Curtir <i style="<?= ($curtida->verificaCurtida($postagem['postagemId'], $usuarioCurtiu)) ? 'color:red' : 'color:black' ?>" id="curtirPost<?php echo $postagem['postagemId'] ?>" class="far fa-heart"></i></span>
                        <span onclick="esconderMostrarContainer('comentarPost<?php echo $postagem['postagemId'] ?>')" id="comentarPost<?php echo $postagem['postagemId'] ?>">Cometarios <span><?= $comentarios->getTotComentarios($postagem['postagemId']) ?></span><i class="far fa-comment-alt"></i></span>
                        <span id="compartilharPost<?php echo $postagem['postagemId'] ?>">Compartilhar <i class="fas fa-share-alt"></i></span>

                        <span style="position:absolute;right:0px; cursor:none"><span id="totCurtidas<?= $postagem['postagemId'] ?>"><?php echo  $curtida->getTotalCurtida($postagem['postagemId']) ?></span> <i class="far fa-heart"></i></span>

                    </div>
                </div>
            </div>
        </div>
        <hr />
        <!-- comentarios da postagem -->
        <div class="postagemComentarioId" id="postagemComentariosId<?=$postagem['postagemId']?>">
        <div id="containerComentarios" class="hideComentarios">
            <input class="comentarioIdPostagem" hidden type="text" value="<?= $postagem['postagemId'] ?>">
            <div id="containerComentariosInner">

            </div>


            <div class="verMaisComentarios">
                <?php if($comentarios->getTotComentarios($postagem['postagemId']) >0){ ?>
                    <i class="fas fa-long-arrow-alt-right"></i>
                    <a onclick="carregarComentariosAjax(this)" style="cursor:pointer;" >Carregar Comentarios</a>              
                 <?php }?>
            </div>
 
                                          
            
            <div class="seuComentario">
                <form action="/salvarcomentario" method="post">
                    <div class="containerArquivoSeuComentario">

                    </div>
                    <input id="textSeuComentario<?= $postagem['postagemId'] ?>" class="textSeuComentario" type="text" placeholder="Escreva um comentário" name="textSeuComentario">
                    <div style="display: inline; color:#777;position:absolute;right:30px;">
                        <input name="idPostagemComentario" type="text" value="<?= $postagem['postagemId'] ?>" hidden>
                        <input onchange="carregarArquivosComentario(this,'<?= $postagem['postagemId'] ?>')" name="arquivoComentarioUpload" type="file" accept="image/*,video/*" class="arquivoComentarioUpload" id="arquivoComentarioUpload<?= $postagem['postagemId'] ?>" hidden />
                        <label style="cursor: pointer;" for="arquivoComentarioUpload<?= $postagem['postagemId'] ?>"><i class="fas fa-images fa-1x"></i></label>
                    </div>
                </form>

            </div>
        </div>

        </div>

    </div>




</div>