<?php
use MF\Controller\Action;
use MF\Model\Container;

//   echo '<br/>';
//   print_r($_SESSION);
//   echo '<br/>';
//   print_r($this->view);

//   echo $this->view->user_picture;
require_once('../../miniframework/App/Utils.php');
Utils::verificarLogado();

date_default_timezone_set('America/Sao_Paulo');
$comentarios=Container::getModel('comentario');
$comentariosDosComentarios=Container::getModel('ComentarComentarios');
?>

<!-- navegacao menu -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
 
	<a class="nav-link" href="#"><img width="80px" class="img-fluid" src="../public/img/logo/logo_2.png"> </a>
 
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
		<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
			
			<li class="nav-item ">
				<a class="nav-link" href="#">Home </a>
			</li>
			<li class="nav-item">
				<a class="nav-link disabled" href="/miniframework/public/perfil">Perfil</a>
			</li>

			<li class="nav-item">
				<a class="nav-link disabled" href="/miniframework/public/configuracao">Configuraçoes de conta</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/miniframework/public/logOut">Sair</a>
			</li>
			<li class="nav-item d-sm-block d-md-none">
				<a style="cursor:pointer" onclick="mostrarChat()" class="nav-link d-sm-block d-md-none">Mensagem</a>
			</li>
		</ul>

		 <div class="d-none d-md-block" style="z-index:200000000000000000000000000;position: fixed; bottom: 15px; right:15px;cursor:pointer">
		 	<a style="text-decoration: none;color:black" target="_blank" href="/miniframework/public/mensagem"><i    class="fas fa-comments fa-2x d-none d-md-block"></i></a>

		</div>

		<form id="pesquisarUsuarios" class="form-inline my-2 my-lg-0" method="post" action="/pesquisarUsuarios">
			<input id="pesquisarPorTimeline" class="form-control mr-sm-2" type="search" placeholder="Search" name="pesquisarpor">
		   
		</form>
	</div>
</nav>
<!-- seta de subir  -->
<div id="back-to-top" onclick="subirRolagem()" style="z-index:200000000000000000000000000;position: fixed; bottom: 15px; left:15px;cursor:pointer">
	<i style="margin: 0px; padding:0px"   class="fas fa-sort-up fa-2x d-flex justify-content-center"></i>
	<p style="margin: 0px; padding:0px"><strong>Subir</strong></p>
</div>

<!-- CHAT DO APLICATIVO -->


<!-- timelineConteudo -->
<div class="container mt-5">
	<div class="row pt-2">
		<!-- topo imagem,seguidores,postagens ,seguindo -->
		<div style="position:relative;left:-100px" class="col-md-3" id="menuUsuarioContainer">

			<div id="profile" style="z-index: 11;">
				<div class="perfilTopo">
					<form method="post" enctype="multipart/form-data" id="uploadPic">
						<input type="file" name="imgInp" accept="image/x-png,image/jpge,image/jpg" id="imgInp" hidden>
						<div class="pictureContainer">
							<img id="userImg" src="../public/img/user/<?php echo $this->view->user_picture ?>" />
							<label for="imgInp"></label>
						</div>
					</form>
				</div>

				<div class="perfilPainel">

					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $this->view->user_username?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Postagens</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->totPostagens?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->totSeguindo?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->totSeguidores?></span>
						</div>

					</div>

				</div>
			</div>

			<div  id="seusAmigos" class="col-md-3 d-none d-lg-block" style="position:fixed; left:0px; top:20%;display:none;z-index:-10">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Seus amigos <i class="fas fa-globe-asia"></i></span><br />
				<hr />
				<div class="row" >
					<div class="col" style="height:300px;overflow:auto" id="containerSeusAmigos">
						<?php foreach ($this->view->amigos as $key => $user) {  ?>
							<div class="row serchContainerMenu mb-4">
								<div class="searchContainer col">
									<img style="cursor:pointer;" onclick="location.href='/miniframework/public/perfil?idUsuario=<?=$user['id']?>'"  src="../public/img/user/<?=$user['picture']?>">
									 <?php if($user['onlineSN']=='s'){?>
											<p class="textUserSeguir" ><i style="color: greenyellow;" class="fas fa-circle"></i> Online  a <?=$comentarios->timing(strtotime($user['online'])) ?> </p>
									 <?php }else{ ?>

											<p class="textUserSeguir" ><i style="color: #777;" class="fas fa-circle"></i> Offline </p>

									 <?php }?>
								</div>


							</div>
						<?php } ?>
					</div>

				</div>
			 </div>
			 <form style="width: 100%;" id="pesquisarUsuarios" class="form-inline my-2 my-lg-0" method="post" action="/pesquisarAmigos">
					<input style="width: 100%;" id="pesquisarPorAmigos" class="form-control mr-sm-2" type="search" placeholder="Procurar Amigos" name="pesquisarpor">
		   
			</form>
		</div>

		</div>
		<!-- fim -->

	 
		<div class="col-md-6">
			<div class="row mb-2">
				<!-- //Criação de postagem -->
				<div class="col tweetBox">


					<form id="formularioPostagem" method="post" enctype="multipart/form-data" action="miniframwork/postagem">
					
						<textarea id="textTweet" name="postagemTextArea" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
						<div   style="color:white;background-color:#17A2B8;margin-top:15px;display: inline-block; border-radius:20px;color:black;padding:1px;padding-left:4px;padding-right:4px">
								 
						        <input onclick="verChecado(this)" style="line-height:50%;border:none;" name="postVendas" type="checkbox" id="postVendas">
								<label  style="line-height:50%;color:white" for="postVendas">Postagem Venda</label>
						</div>
						<!-- //container da imagem q vai ser carregada -->

						<div class="row mt-4">
							<div class="col">
								<div class="d-flex justify-content-end">
									<i id="fecharArquivoUpload" class="fas fa-times fa-lg"></i>
								</div>

								<div id="arquivoUpload" class="d-flex justify-content-center">
								</div>
							</div>
						</div>
						<!-- //criar postagem e foto -->
						<div class="d-flex justify-content-between mt-4">

							<div class="" id="containerImgPostagemUpload">
								<input name="imgPostagem" onchange="carregarArquivosPostagem(this)" type="file" accept="image/*,video/*" id="arquivoPostagemUpload" hidden />
								<label for="arquivoPostagemUpload"><i class="fas fa-images fa-2x"></i></label>
							</div>


							<div class="">
								<button id="buttonTweet" type="submit" class="btn btn-outline-info justify-content-end">Criar Postagem</button>

							</div>
						</div>

					</form>

				</div>
			</div>

			<!-- //botoes social e vendas -->
			<div class="col-md-12 mt-4">
					<div id="galeria">
						<!-- Grid row -->
						<div class="row">

							<!-- Grid column -->
							<div class="col-md-12 d-flex justify-content-center mb-5">
								<button id="botaoSocial" style="cursor: pointer;"   onclick="socialPostagens();"  type="button" class="btn btn-outline-black waves-effect filter botaoAtivo" data-rel="postagens">Social</button>

								<button id="botaoVendas" style="cursor: pointer;" onclick="vendasPostagens()" type="button" class="btn btn-outline-black waves-effect filter" data-rel="all">Vendas</button>
								

							</div>
							<!-- Grid column -->

						</div>
						<!-- Grid row -->

						<!-- Grid row -->
						<div class="gallery" id="gallery">


						</div>
						<!-- Grid row -->

					</div>




				</div>



        <!-- postagens de todo mundo -->
			<div id="postagem">
				
				   <?php  foreach ($this->view->postagens as $key => $postagem) { ?>
					   <?php include('postagem.phtml') ?>
				   <?php }?>
                   
			</div>
			<div id="loadingPostagens" class="d-flex justify-content-center">
               <img width="60px" height="60px" src="../public/gif/2.gif">
			</div>

			<div id="errorPostagens" class="d-flex justify-content-center d-none">
                  <p>Nao tem mais publicaçoes para vôce</p><img width="48px" height="48px"  src="../public/img/outros/empty-inbox.png"/>
			</div>

			 

		</div>
		<!-- fim postagens -->

		<!-- quem seguir -->
		<div id="quemSeguir" class="col-md-3 d-none d-lg-block" style="position:fixed;right:0px">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<div class="row">
					<div class="col">
						<?php foreach ($this->view->quemSeguir as $key => $user) {  ?>
							<div class="row serchContainerMenu mb-4">
								<div class="searchContainer col">
									<img style="cursor:pointer;" onclick="location.href='/miniframework/public/perfil?idUsuario=<?=$user['id']?>'"  src="../public/img/user/<?=$user['picture']?>">
									<p class="textUserSeguir" style="cursor:pointer;" onclick="location.href ='/miniframework/public/perfil?idUsuario=<?=$user['id']?>'"><?=$user['name'] ?></p>
            
								</div>


							</div>
						<?php } ?>
					</div>

				</div>
				<a style="color:black" href="/miniframework/public/quemseguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>
		<!-- fim quem seguir -->

	</div>
	<div style="display:none" class="row" id="pesquisaLateral">
		<div class="col" id="containerPesquisaLateral">

		</div>
	</div>
</div>

<script charset="utf-8" src="../public/js/timeline.js"></script>
<script charset="utf-8" src="../public/js/quemseguir.js"></script>
