
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8" />
	<title>Miniframework</title>


	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script charset="utf-8" src="../public/js/sweetalert.js"></script>
	<script charset="utf-8" src="../public/js/perfil.js"></script>
	<script charset="utf-8" src="../public/js/quemseguir.js"></script>
	<script charset="utf-8" src="../public/js/timeline.js"></script>
	<script charset="utf-8" src="../public/js/loginERegistro.js"></script>


	<link rel="stylesheet" type="text/css" href="../public/css/global.css">
	<link rel="stylesheet" type="text/css" href="../public/css/perfil.css">
	<link rel="stylesheet" type="text/css" href="../public/css/timeline.css">
	<link rel="stylesheet" type="text/css" href="../public/css/quemseguir.css">
	<link rel="stylesheet" type="text/css" href="../public/css/loginERegistro.css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <script>
            
	</script>
	

</head>

<body>
	<?= $this->content() ?>
</body>

</html>